apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: statefulset-mysql
spec: # Devemos expecificar o padrão o objeto ue será abstraído pelo "StatefulSet "
  serviceName: db
  template:
    metadata: # Devemos especificar o objeto "POD" que criamos para representar o banco.
      labels:
       name: mysql
    spec:
      containers:
        - name: container-mysql
          image: mysql:5.7.19
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "loja"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "1"
          volumeMounts:
            - name: volume-mysql
              mountPath: /var/lib/mysql # local onde no bando de dados as informações ficam armzenadas
      volumes:
       - name: volume-mysql
         persistentVolumeClaim:
           claimName: configuracao-mysql
